language: java

script: mvn -B install

jdk:
- openjdk17

services:
  - docker

sudo: required

notifications:
  slack:
    on_failure: always
    on_success: always
    secure: YUeHcLIxXFLOokSc8ljuRWfA8q02+1Us8dalaRLWatJXqnGTGasbPc7PPeg0/hesjJA6j4KTohbtLCjt0Eto+wR5ENG5Yeyy7tP3FlWPA2AQJ4Xl71zqrKO9q8C/FDw6dKJxXeEbACN7HFvBETrQ6643bNbz559FQA2iQOLi6fk4fMJs04GQBGj1zosvCVJTafzRuReYau5kfyBGqnVBDTnmoNYirgMFAyeg8mTM5NAUWPfDdl4r6DzdXKIGV05wgLzDOdDwhJmBcrFAKss5xv49aIbPTzCyQbOqNgOBUy1sXjNI8RMRgkUtFnU+FRQXFx5jsCJwvwdWBHyFjxKaJvz14ZYqKb8i4GRLdUj95FbWKvJnmexaoCkA9MbyqO6SLtviqhTl8oZjLUdfMX7htJgJtjM0u1A+ZbaHH7NsTNVtfdlCYTQ4M1ZZHy/cTPQ08OIe62nrbcQiCWuOTxukhZnRO5pctmI9BZGVhGNSxssDlM5vFMacQMXBEHGKq8PqtyLP7bzJriX1rSUFXwsCp5SYqozvcrvsy7wOK5mHhiUDQmadXNQXb3evha7uJ+u402AlkCObLULLoAs6yRZzL1g9C8hNRp8gplj7+ni9rvGtr4vZi7Gp/HnENhqUcP7/LbY6RKH9npFm6QlYoaLDOcFC6Ky4JnK749NtHqP3+bY=
